services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: smarthub-backend-dev
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: smarthub-frontend-dev
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
